name: Sync fork with upstream (Equicord)

on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        run: gh repo sync $GITHUB_REPOSITORY --source Equicord/Equicord --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
